services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: josi
      MONGO_INITDB_ROOT_PASSWORD: letmepass!!42
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: josi
      ME_CONFIG_MONGODB_ADMINPASSWORD: letmepass!!42
      ME_CONFIG_MONGODB_URL: mongodb://josi:letmepass!!42@mongo:27017/
