stages:
 - stage: Provision
   jobs:
   - job: Provision
     variables:
     - group: Terraform
     steps:
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: |
           terraform init -input=false
           terraform apply -auto-approve
 - stage: Build
   jobs:
   - job: Build
     steps:
     - task: DotNetCoreCLI@2
       inputs:
         command: 'build'
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'
     - task: DotNetCoreCLI@2
       inputs:
         command: 'publish'
         publishWebProjects: true
         arguments: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
         zipAfterPublish: True
     - task: AzureWebApp@1
       inputs:
         azureSubscription: 'Betalt efter forbrug(fd949dc3-162d-4991-a986-02631830a313)'
         appType: 'webAppLinux'
         appName: 'josi-architecture-webapi'
         deployToSlotOrASE: true
         resourceGroupName: 'josi-architecture-resource-group'
         slotName: 'development'
         package: '$(Build.ArtifactStagingDirectory)/*.zip'
         runtimeStack: 'DOTNETCORE|7.0'
         startUpCommand: 'dotnet run'

