stages:
 - stage: Provision
   jobs:
   - job: Provision
     variables:
     - group: Terraform
     steps:
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: |
           terraform init -input=false
           terraform apply -auto-approve
 - stage: BuildAndDeploy
   jobs:
   - job: BuildAndDeploy
     pool: 'windows-latest'
     steps:
     - task: DotNetCoreCLI@2
       inputs:
         command: 'build'
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'
     - task: DotNetCoreCLI@2
       inputs:
         command: 'publish'
         publishWebProjects: false
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'
         arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
     - task: AzureRmWebAppDeployment@4
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'Betalt efter forbrug(fd949dc3-162d-4991-a986-02631830a313)'
         appType: 'webApp'
         WebAppName: 'josi-architecture-webapi'
         packageForLinux: '$(Build.ArtifactStagingDirectory)'
         enableCustomDeployment: true
         DeploymentType: 'webDeploy'

