# Empty ci build file for now

stages:
 - stage: Build
   jobs:
   - job: Build
     steps:
     - task: DotNetCoreCLI@2
       inputs:
         command: 'build'
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'