stages:
 - stage: Provision
   jobs:
   - job: Provision
     variables:
     - group: Terraform
     steps:
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: |
           terraform init -input=false
           terraform apply -auto-approve
 - stage: Publish
   jobs:
   - job: Publish
     displayName: 'Publish api artifact for release'
     steps:
     - task: DotNetCoreCLI@2
       displayName: 'Publish the Api project'
       inputs:
         command: 'publish'
         publishWebProjects: false
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'
         arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
         zipAfterPublish: True
     - task: PublishBuildArtifacts@1
       displayName: 'Publish build artifact'
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'

