stages:
 - stage: Build
   jobs:
   - job: Build
     steps:
     - task: DotNetCoreCLI@2
       inputs:
         command: 'build'
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'
   - job: Provision
     variables:
     - group: Terraform
     steps:
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: |
           terraform init -input=false
           terraform apply -auto-approve