stages:
 - stage: Provision
   variables:
    - name: angular_site_api_key
      value: initial_angular_site_api_key
   jobs:
   - job: Provision
     variables:
     - group: Terraform
     steps:
     - task: PowerShell@2
       name: terraform
       inputs:
         targetType: 'inline'
         script: |
           terraform init -input=false
           #  #terraform apply -auto-approve -target="azurerm_windows_web_app.josi_architecture_webapi"
           #  #terraform apply -auto-approve
           #  terraform apply -auto-approve -target="azurerm_static_site.josi_architecture_angular_site"
           terragrunt run-all apply -auto-approve
           Write-Host "##vso[task.setvariable variable=angular_site_api_key;isOutput=true]$((terraform output angular_site_api_key).Trim().Replace('"', ''))"
 - stage: Api
   jobs:
   - job: PublishAndDeploy
     displayName: 'Build and deploy Api'
     steps:
     - task: DotNetCoreCLI@2
       displayName: 'Publish the Api project'
       inputs:
         command: 'publish'
         publishWebProjects: false
         projects: 'src/JosiArchitecture.Api/JosiArchitecture.Api.csproj'
         arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
         zipAfterPublish: True
     - task: PublishBuildArtifacts@1
       displayName: 'Publish build artifact'
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'
     - task: AzureRmWebAppDeployment@4
       displayName: 'Deploy Api to Azure App Service'
       inputs:
         azureSubscription: 'Betalt efter forbrug(fd949dc3-162d-4991-a986-02631830a313)'
         appType: 'webApp'
         webAppName: 'josi-architecture-webapi'
         package: '$(Build.ArtifactStagingDirectory)/**/JosiArchitecture.Api.zip'
 - stage: Angular
   dependsOn: Provision
   variables:
    angular_site_api_key: $[ stageDependencies.Provision.Provision.outputs['terraform.angular_site_api_key'] ]
    bingo: bango
   jobs:
   - job: Angular
     displayName: Build and deploy Angular app
     steps:
       - task: PowerShell@2
         inputs:
           targetType: 'inline'
           script: | 
             echo "Deploying to static web app using token:"
             echo $(angular_site_api_key)
       - task: AzureStaticWebApp@0
         inputs:
           azure_static_web_apps_api_token: $(angular_site_api_key)
           app_location: '/src/JosiArchitecture.AngularApp'
           output_location: '/dist/josi-architecture.angular-app'           