version: "3.8"
services:
    database:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1433:1433
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=letmepass!!42
            - MSSQL_PID=Developer