apiVersion: v1
kind: Service
metadata:
  labels:
    service: kibana
  name: kibana
  namespace: josi
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 32561
  selector:
    service: kibana
