apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kibana
  name: kibana
  namespace: josi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kibana
  strategy: {}
  template:
    metadata:
      labels:
        network/josi-architecture-default: "true"
        service: kibana
    spec:
      containers:
        - image: kibana:8.10.2
          imagePullPolicy: IfNotPresent
          name: kibana
          ports:
            - containerPort: 5601
              hostPort: 5601
              protocol: TCP
          resources: {}
      restartPolicy: Always
