apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: webapi
  name: webapi
  namespace: josi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  strategy: {}
  template:
    metadata:
      labels:
        network/josi-architecture-default: 'true'
        service: webapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
          image: webapi:latest
          imagePullPolicy: Never
          name: webapi
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
