apiVersion: v1
kind: Service
metadata:
  labels:
    service: webapi
  name: webapi
  namespace: josi
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
  selector:
    service: webapi
