services:
  webapi:
    build:
      context: ../apps/api-dotnet
      dockerfile: src/JosiArchitecture.Api/Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '8010:80'
      - '44311:443'
    volumes:
      - ./../certs:/certs
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=44311
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/localhost.pfx
  api-nest:
    build:
      context: ../
      dockerfile: ./apps/api-nest/Dockerfile
    depends_on:
      mongo:
        condition: service_started
    ports:
      - '44310:44310'
    environment:
      - PORT=44310
      - HOST=0.0.0.0
      - SSL=true
      - SSL_KEY_PATH=../../../certs/localhost-key.pem
      - SSL_CERT_PATH=../../../certs/localhost.pem
      - DATABASE_CONNECTIONSTRING=mongodb://josi:letmepass!!42@mongo:27017/
