apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: sqlserver
  name: sqlserver
  namespace: josi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sqlserver
  strategy: { }
  template:
    metadata:
      labels:
        network/josi-architecture-default: "true"
        service: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: { }
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: letmepass!!42
      restartPolicy: Always