apiVersion: v1
kind: Service
metadata:
  labels:
    service: database
  name: database
  namespace: josi
spec:
  type: NodePort
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
      nodePort: 31433
  selector:
    service: database
