apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: database
  name: database
  namespace: josi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  strategy: {}
  template:
    metadata:
      labels:
        network/josi-architecture-default: "true"
        service: database
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: letmepass!!42
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: database
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
      restartPolicy: Always