apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres
  name: postgres
  namespace: josi
spec:
  type: NodePort
  ports:
    - name: '5432'
      port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    service: postgres
