apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: elasticsearch
  name: elasticsearch
  namespace: josi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch
  strategy: {}
  template:
    metadata:
      labels:
        network/josi-architecture-default: 'true'
        service: elasticsearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: 'single-node'
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.security.enrollment.enabled
              value: 'false'
            - name: ES_JAVA_OPTS
              value: '-Xms750m -Xmx750m'
          image: elasticsearch:8.10.2
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
            - containerPort: 9300
              hostPort: 9300
              protocol: TCP
          resources: {}
      restartPolicy: Always
