name: CICD
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install pnpm packages
        run: pnpm install
      - name: Lint
        run: npx nx run-many -t lint --verbose
      - name: Build
        run: npx nx run-many -t build  --verbose
      - name: Start containers
        run: docker-compose -f "docker/infra.docker-compose.yml" -f "docker/api.docker-compose.yml" up -d --build
      - name: End-to-end Api Test
        run: npx nx api-e2e api-nest-e2e --verbose
      - name: Stop containers
        run: docker-compose -f "docker/infra.docker-compose.yml" -f "docker/api.docker-compose.yml" down
