name: CICD
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: master
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install pnpm packages
        run: pnpm install
      - name: Lint
        run: npx nx affected -t lint --base=master --head=HEAD --parallel=3
      - name: Build
        run: npx nx affected -t build --base=master --head=HEAD --parallel=3
      # - name: Start containers
      #   run: docker-compose -f "docker/infra.docker-compose.yml" -f "docker/api.docker-compose.yml" up -d --build
      # - name: Test Nest Api
      #   run: npx nx run api-test:api-e2e-nest
      # - name: Test Dotnet Api
      #   run: npx nx run api-test:api-e2e-dotnet
      # - name: Stop containers
      #   run: docker-compose -f "docker/infra.docker-compose.yml" -f "docker/api.docker-compose.yml" down
