name: CICD
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  install:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g pnpm
      - run: pwd
      - run: ls -la
      - run: pnpm install
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npx nx run-many -t lint
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npx nx run-many -t build

